config/routes.rb
CodingTable::Application.routes.draw do
  get "home/index"

  get "home/admin"

  

  resources :categories

  resources :languages

  root :to => "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  USER_ID, PASSWORD = 'coding', 'table'

  private

  def authenticate
    authenticate_or_request_with_http_basic do |id, password|
      id == USER_ID && password == PASSWORD
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate

  layout 'admin'
  
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate, :only => "admin"


  layout "application"

  def index
    @languages = Language.all
    @heights = [9, 9, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 8, 8]
    @columns = Array.new

    @heights.each_with_index do |h, index|
      @columns << @languages.slice!(0, h)
    end

   if @columns.last.empty?
        @columns.pop
    end

#    @heights.each_with_index do |h, index|
#    eval("#{@column+index.to_s} = #{@languages.slice!(0, h)}")
#    end
  end

  def admin
  end

#  def import2
#
#    file = params[:file]
#
#    File.open(file).each do |l|
#     # line = Array.new
#      line = l.split( /,/)
##      if Category.find_by_name(line[1].to_s).nil?
##      new_category = Category.create(:name => line[1].to_s)
##      category_id = new_category.id
##      else
##        category_id = Category.find_by_name(line[1].to_s).id
##      end
#
#      category_id = Category.find_or_create_by_name(line[1].to_s).id
#
#
#      if line[3].nil? || line[3].empty?
#      abbreviation = line[0].slice(0,2).capitalize
#      else
#      abbreviation = line[3].to_s
#      end
#      Language.create(:name => line[0].to_s, :category_id => category_id.to_i, :year => line[2].to_i, :abbreviation => abbreviation)
#    end
#  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  before_filter :authenticate

  layout 'admin'

  # GET /languages
  # GET /languages.xml
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.xml
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.xml
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.xml
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to(@language, :notice => 'Language was successfully created.') }
        format.xml  { render :xml => @language, :status => :created, :location => @language }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.xml
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to(@language, :notice => 'Language was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.xml
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to(languages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/admin.html.erb
<h1>Home#admin</h1>
<p>Find me in app/views/home/admin.html.erb</p>

<p>
	<!-- admin controls -->
  <b>Admin controls</b>
  <br />
<%= link_to 'Languages', :controller => "languages", :action => "index" %>
<%= link_to 'Categories', :controller => "categories", :action => "index" %>
</p>

app/views/home/import.html.erb
<%=  form_tag 'import2', :multipart => true do %>
<%= file_field_tag "file" %>
<%= submit_tag %>
<% end %>

app/views/home/index.html.erb
<!-- Javascript with Embedded Ruby / Won't work in .js file-->
  <script language="javascript" type="text/javascript">
 /*-------------------------------------------------------------------------------------------------
	Global Variables
   -------------------------------------------------------------------------------------------------*/
	var red = '#F77C88';
	var orange = '#FF9700';
	var yellow = '#FFE600';
	var green = '#CFFF5A';
	var blue = '#54B9DD';
	var purple = '#A05DDB';
	var magenta = '#ED5DE3';

  /*-------------------------------------------------------------------------------------------------
	Dropdown Menus
   -------------------------------------------------------------------------------------------------*/
	window.addEvent('domready', function(){
		$('drop_down_menu').getElements('li.menu').each( function( elem ){
			var list = elem.getElement('ul.links');
			var myFx = new Fx.Slide(list).hide();
			elem.addEvents({
				'mouseenter' : function(){
					myFx.cancel();
					myFx.slideIn();
				},
				'mouseleave' : function(){
					myFx.cancel();
					myFx.slideOut();
				}
			});
		})
	});


 /*-------------------------------------------------------------------------------------------------
	colorYears(): Arranges colors by year
  -------------------------------------------------------------------------------------------------*/
	function colorYears(){
		var id = '';
		var year = '';
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			year = "<%= l.year %>";
			if(year<1960)
				$(id).tween('background-color', red);
			else if(1960<=year && year<1970)
				$(id).tween('background-color', orange);
			else if(1970<=year && year<1980)
				$(id).tween('background-color', yellow);
			else if(1980<=year && year<1990)
				$(id).tween('background-color', green);
			else if(1990<=year && year<2000)
				$(id).tween('background-color', blue);
			else if(2000<=year && year<2010)
				$(id).tween('background-color', purple);
			else if(2010<=year && year<2020)
				$(id).tween('background-color', magenta);
			<% end %>
	 	<% end %>
	}


	/*-------------------------------------------------------------------------------------------------
	colorCategories(): Arranges categories by year
  -------------------------------------------------------------------------------------------------*/
	function colorCategories(){
		var id = '';
		var cat = '';
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			cat = "<%= l.category.name %>";
			if(cat == 'Esoteric')
				$(id).tween('background-color', red);
			else if(cat=='Object Oriented')
				$(id).tween('background-color', orange);
			else if(cat=='Procedural')
				$(id).tween('background-color', yellow);
			else if(cat=='Compiled')
				$(id).tween('background-color', green);
			else if(cat=='Functional')
				$(id).tween('background-color', blue);
			else if(cat=='Scripting')
				$(id).tween('background-color', purple);
			else if(cat=='Other')
				$(id).tween('background-color', magenta);
			<% end %>
	 	<% end %>
	}

/*-------------------------------------------------------------------------------------------------
  highlightYear(): highlights colors by year
  -------------------------------------------------------------------------------------------------*/
	function highlightYear(arg){
		var id = '';
		var year = '';

		//first revert everything to black
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			id = id+'nameLabel';
			$(id).tween('background-color', '#333333');
                        $(id).style.color='#FFFFFF';
			<% end %>
	 	<% end %>

		//then apply any necessary colors
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			year = "<%= l.year %>";
			if(arg <= year && year < arg+10){
				id = id+'nameLabel';
				$(id).tween('background-color', '#FFFFFF');
                                $(id).style.color='#000000';
			}
			<% end %>
	 	<% end %>
	}


	/*-------------------------------------------------------------------------------------------------
  highlightCategory(): highlights colors by category
  -------------------------------------------------------------------------------------------------*/
	function highlightCategory(arg){
		var id = '';
		var cat = '';

		//first revert everything to black
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			id = id+'nameLabel';
			$(id).tween('background-color', '#333333');
                        $(id).style.color='#FFFFFF';
			<% end %>
	 	<% end %>

		//then apply any necessary colors
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			cat = "<%= l.category.name %>";
			if(arg == cat){
				id = id+'nameLabel';
				$(id).tween('background-color', '#FFFFFF');
                                $(id).style.color='#000000';
			}
			<% end %>
	 	<% end %>
	}


  /*-------------------------------------------------------------------------------------------------
  resetColors(): changes cell colors to original config
  -------------------------------------------------------------------------------------------------*/
	function resetColors(){
		var id='';
		var col=0;
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
		  		id = "<%= l.name %>";
				col = <%=  i %>;

				if(col<=1)
					$(id).tween('background-color', red);
				else if(col<=3)
					$(id).tween('background-color', orange);
				else if(col<=8)
					$(id).tween('background-color', yellow);
				else if(col<=11)
					$(id).tween('background-color', green);
				else if(col<=14)
					$(id).tween('background-color', blue);
				else if(col<=15)
					$(id).tween('background-color', purple);
				else if(col<=16)
					$(id).tween('background-color', magenta);

				id = id+'nameLabel';
				$(id).tween('background-color', '#333333');
                                $(id).style.color='#FFFFFF';
			<% end %>
	 	<% end %>

		//first revert everything to black
		<% @columns.each_with_index do |c, i| %>
	  		<% c.each do |l| %>
	  		id = "<%= l.name %>";
			id = id+'nameLabel';
			$(id).tween('background-color', '#333333');
			<% end %>
	 	<% end %>
	}

</script>


<p>

<!-- =========================== HTML STARTS HERE ===================================-->

<!-- legend -->

<h1>Programming Languages: 1950's - Present</h1>

<div class="header">
	<div id="menu-container">
		<ul id="drop_down_menu">
			<li class="menu" onclick="resetColors()">Reset
				<ul class="links">

				</ul>
			</li>
			<li class="menu"><span onmousedown="colorYears()">Year</span>
				<ul class="links">
					<li><a href="javascript:highlightYear(1950)">1950s+older</a></li>
					<li><a href="javascript:highlightYear(1960)">1960s</a></li>
					<li><a href="javascript:highlightYear(1970)">1970s</a></li>
					<li><a href="javascript:highlightYear(1980)">1980s</a></li>
					<li><a href="javascript:highlightYear(1990)">1990s</a></li>
					<li><a href="javascript:highlightYear(2000)">2000s</a></li>
					<li><a href="javascript:highlightYear(2010)">2010s</a></li>
				</ul>

			</li>
			<li class="menu"><span onmousedown="colorCategories()">Category</span>
				<ul class="links">
					<li><a href="javascript:highlightCategory('Esoteric')">Esoteric</a></li>
					<li><a href="javascript:highlightCategory('Object Oriented')">Object Oriented</a></li>
					<li><a href="javascript:highlightCategory('Procedural')">Procedural</a></li>
					<li><a href="javascript:highlightCategory('Compiled')">Compiled</a></li>
					<li><a href="javascript:highlightCategory('Functional')">Functional</a></li>
					<li><a href="javascript:highlightCategory('Scripting')">Scripting</a></li>
					<li><a href="javascript:highlightCategory('Other')">Other</a></li>

				</ul>
			</li>

		</ul>
	</div>
</div>

	<!-- create the cells by looping through the double array-->
 <% @columns.each_with_index do |c, i| %>
	<div class="column" id="column<%=  i %>">
  	<% c.each do |l| %>
  		<div class="<%= l.category.name.downcase %> cell cellcolumn<%=  i %>" id="<%= l.name %>"
  		onclick="clearColor('<%= l.name %>')" >
	  		<div class="nameLabel" id="<%= l.name %>nameLabel"><%= l.name  %></div>
	  		<div class="symbol"><%= l.abbreviation %></div>
  		</div>
	<% end %>
	</div>
 <% end %>

</p>

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
<p>
  <%= link_to "create Category", new_category_path %>
</p>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
 <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Category</th>
    <th>Abbreviation</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= language.year %></td>
    <td><%= Category.find(language.category_id).name %></td>
    <td><%=  language.abbreviation %></td>
    <td><%= language.url %></td>
    <td><%= link_to 'Show', language %></td>
    <td><%= link_to 'Edit', edit_language_path(language) %></td>
    <td><%= link_to 'Destroy', language, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @language.name %>
</p>

<p>
  <b>Year:</b>
  <%= @language.year %>
</p>

<p>
  <b>Category:</b>
  <%= Category.find(@language.category_id).name %>
</p>

<p>
  <b>Url:</b>
  <%= @language.url %>
</p>


<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingTable</title>
  <!--
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/mootools/1.2.1/mootools-yui-compressed.js"></script>
  -->
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%#*prototype conflicts with mootools%>
  <%#= javascript_include_tag 'cellscript.js' %>
  <%#= javascript_include_tag 'mootools-1.2-core.js' %>
  <%#= javascript_include_tag 'mootools-1.2-more.js' %>

  <%= csrf_meta_tag %>
  <script type="text/javascript">
  var uservoiceOptions = {
    key: 'codingtable',
    host: 'codingtable.uservoice.com',
    forum: '103887',
    alignment: 'right',
    background_color:'#0066cc',
    text_color: 'white',
    hover_color: '#FF9700',
    lang: 'en',
    showTab: true
  };
  function _loadUserVoice() {
    var s = document.createElement('script');
    s.src = ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js";
    document.getElementsByTagName('head')[0].appendChild(s);
  }
  _loadSuper = window.onload;
  window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21634592-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body onload="resetColors()">

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingTable</title>
  <!--
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/mootools/1.2.1/mootools-yui-compressed.js"></script>
  -->
  <%= stylesheet_link_tag :all %>
  <%#= javascript_include_tag :all %>
  <%= javascript_include_tag 'cellscript.js' %>
  <%= javascript_include_tag 'mootools-1.2-core.js' %>
  <%= javascript_include_tag 'mootools-1.2-more.js' %>
  
  <%= csrf_meta_tag %>
  <script type="text/javascript">
  var uservoiceOptions = {
    key: 'codingtable',
    host: 'codingtable.uservoice.com',
    forum: '103887',
    alignment: 'right',
    background_color:'#0066cc',
    text_color: 'white',
    hover_color: '#FF9700',
    lang: 'en',
    showTab: true
  };
  function _loadUserVoice() {
    var s = document.createElement('script');
    s.src = ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js";
    document.getElementsByTagName('head')[0].appendChild(s);
  }
  _loadSuper = window.onload;
  window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
</script>


</head>
<body onload="resetColors()">

<%= yield %>

</body>
</html>